inherit_from:
#  - .rubocop_todo.yml
#  - enabled.yml
#  - disabled.yml

# Common configuration.
AllCops:
  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'bin/*'
    - 'Gemfile.lock'
    - 'vendor/**/*'