# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0630fde446bebab0769cb169ab917cf4f00f37dc0e111106784d521e6c1937d4d04039b0d2315ffbffd78fa1e42f386453e908bc932bb20dbc76e78be60808de

test:
  secret_key_base: 48657c821adce581fa75ff74aea4de854b58aa3fbdff3db4f6fd47e5f58be0981ecc6d18ab900113c9dd2e13ac71906c745a9555f21ab5158d09e3d45d0371cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
